### ISSUE TITLE
Sprint 3 review demo presentation

### ISSUE THREAD

**Issue by Bensge** [AmyAssist/Amy#162]
The sprint review demo has to be a powerpoint presentation. Don't use speech recognition if it could fail. Prepare all the sentences that should be demo'd.

**Comment by Bensge** [comment]
I will present:
* Registry UI in WebApp

**Comment by FlxB2** [comment]
I will present:
* new weather ui design in webapp
* login in webapp
* (maybe agf/nl parser/lexer)

**Comment by FlxB2** [comment]
These are the user stories that should be presented
additional features/changes can be presented too

* [Improve existing functionalities](https://github.com/AmyAssist/Amy/issues/73) #73
* [Spotify improvements](https://github.com/AmyAssist/Amy/issues/83) #83 
* [Registry](https://github.com/AmyAssist/Amy/issues/84) #84 
* [Study recognizability of speech over different methods](https://github.com/AmyAssist/Amy/issues/161) #161 
* [Navigation](https://github.com/AmyAssist/Amy/issues/87) #87 
* [Calendar](https://github.com/AmyAssist/Amy/issues/86) #86 
* [Email](https://github.com/AmyAssist/Amy/issues/85) #85 
* [Smartphone SR](https://github.com/AmyAssist/Amy/issues/81) #81 
* [Prevent Amy from listening when she is talking or music is playing](https://github.com/AmyAssist/Amy/issues/66) #66

**Comment by buddy200** [comment]
i will present:
- new spotify features (rename devices, list featured playlist, list own playlist) #83
- navigation plugin #87

**Comment by neumantm** [comment]
I will present:
 - Slide 11 (Why Stream Speech Audio does not work)
- Interne Änderung: Docker
- Interne Änderung: AudioManager
