### ISSUE TITLE
Dockerize

### ISSUE THREAD

**Issue by neumantm** [AmyAssist/Amy#166]
The project should be deployable with Docker.

Tasks:
- [x] Java App as Dockercontainer(#152)
- [x] Web App as Dockercontainer(https://github.com/AmyAssist/Amy-Web/pull/27)
- [x] Docker Compose
- [x] Docker Hub Account
- [x] Automatic Docker build
- [x] Multi Stage Docker build

**Comment by Legion2** [comment]
where should the docker compose file go?
