### ISSUE TITLE
Calendar refactoring

### ISSUE THREAD

**Issue by Hobbitsloth** [AmyAssist/Amy#179]
Fix SonarCloud Issues like code complexity > 15. Improve Logic class for Web App.

Tasks:
- [x] code complexity of checkDay
- [x] code complexity of eventToString
- [x] method to ask for specific date
- [x] get rid of warning message ([pool-1-thread-1] WARN  c.g.a.c.u.store.FileDataStoreFactory - unable to change permissions for everybody:)

**Comment by Legion2** [comment]
the warning is a bug of Google https://stackoverflow.com/a/34823324/7508057. We just have to disable the logger for the class `com.google.api.client.util.store.FileDataStoreFactory` in our [config](https://github.com/AmyAssist/Amy/blob/dev/core/src/main/resources/logback.xml).
