### ISSUE TITLE
More natural time input

### ISSUE THREAD

**Issue by Bensge** [AmyAssist/Amy#228]
Ability to say "quarter past ten", "half past six", "five past four", "twenty to 9" instead of unnatural "five oh ten" in all plugins that take time input

- [x] Implement logic
- [x] Test with speech

**Comment by FlxB2** [comment]
this could also be done with a custom time rule, I might add that in the next sprint

**Comment by FlxB2** [comment]
why is this closed? The issue is not finished

**Comment by FlxB2** [comment]
PR #310 implements pre defined grammars, inkluding `{amytime}`. Are "quarter past ten", "half past six", "five past four", "twenty to 9" and similar phrases the only options users should have to tell plugins the time?
