### ISSUE TITLE
Implementation of the core components

### ISSUE THREAD

**Issue by FlxB2** [AmyAssist/Amy#23]
implementation of components defined in #7 
- [x] Core
- [x] Storage
- [x] Grammar Generator/Adapter to SR #27 
- [x] Console
- [ ] ~~Text-To-Speech #35~~
- [x] Webserver
- [x] DI

**Comment by Legion2** [comment]
🕐 2h

**Comment by FlxB2** [comment]
Global Plugin Storage added see: 78110b8db5eb3a235cd96b4f7027f1891e4b9914 :clock1: 4h

**Comment by Legion2** [comment]
🕐 8h
