### ISSUE TITLE
Speech Recognition

### ISSUE THREAD

**Issue by sinpat** [AmyAssist/Amy#27]
- [x] Microphone connection
- [x] Wake-up keyword spotting
- [ ] Transform speech input into (wav.-) file
- [ ] Include Speech Rec library
- [x] Grammar management
- [x] Send to fitting Text Parser

**Comment by FlxB2** [comment]
Grammar JSGF File generator was added see: 8080a3854ec992d24b768729815e4000a4307ed9 :clock1: 8h

**Comment by neumantm** [comment]
:clock1: 4h
