### ISSUE TITLE
Sprint 4 Presentation

### ISSUE THREAD

**Issue by Bensge** [AmyAssist/Amy#279]
Presentation with agenda and live demos
* Agenda on a sheet of paper (otherwise Uwe will leave)
* Live demos are well prepared in every detail, no fails and exceptions allowed

**Comment by FlxB2** [comment]
Who will prepare the presentation? I don't have the time for it, but i can present. 
Also we need a list of all things to show and who showcases what.

**Comment by FlxB2** [comment]
Lars and me will present the dialogs
