### ISSUE TITLE
Text Parsing

### ISSUE THREAD

**Issue by sinpat** [AmyAssist/Amy#31]
- [x] Get keywords
- [x] Parse object
- [x] Parse method
- [x] Parse parameters
- [x] Execute function
- [x] If necessary return output

**Comment by FlxB2** [comment]
0850d8cf7ac09f8e401fd3e14c6fedcc3430064d added TextToPlugin class, which maps text to the corresponding @Grammar() annotation. Only thing left is calling the right function
