### ISSUE TITLE
Keyword distribution

### ISSUE THREAD

**Issue by sinpat** [AmyAssist/Amy#33]
- [x] Load plugin keywords
- [x] Create grammar file(s)
- [x] Distribute keyowords to Text Parser

**Comment by Legion2** [comment]
wir haben uns gerade überlegt statt einzelner keywords, sowas ähnliches wie einen regulären Ausdrück zu übergeben und aus dem dann eine Grammatik zu generieren, die der Text Parser verwenden kann.

**Comment by sinpat** [comment]
Ja das wäre nicht schlecht. In dem reg. Ausdruck sind dann auch die keywords drin oder?

**Comment by Legion2** [comment]
https://github.com/AmyAssist/Amy/blob/master/src/main/java/de/unistuttgart/iaas/amyassist/amy/plugin/example/HelloWorld.java
