### ISSUE TITLE
Option to disable cors filter

### ISSUE THREAD

**Issue by Legion2** [AmyAssist/Amy#386]
Make it possible to allow all Origins.

**Comment by Legion2** [comment]
at the same time add a default config for the cors filter

**Comment by Legion2** [comment]
without default config https://github.com/AmyAssist/Amy-All/blob/master/docker/.env#L3 does not work

**Comment by PassaChr** [comment]
to allow all origins use correct cors with access-controll-allow-origin =  "*"
