### ISSUE TITLE
Rich chatbot replies

### ISSUE THREAD

**Issue by Bensge** [AmyAssist/Amy#443]
The Chatbot should provide some rich replies with formatted text, links, and images.

Examples:
What's the weather like in London? => Normal speech reply with small weather info card in the chat bubble.
Play some song ABC => Normal speech reply with album art and song information.
etc.

**Comment by Legion2** [comment]
Maybe we can parse markdown in the chat.

**Comment by FlxB2** [comment]
markdown would be interesting and might be a simple solution for this problem.
