### ISSUE TITLE
Explain the script tools

### ISSUE THREAD

**Issue by Legion2** [AmyAssist/Amy#71]
add explanation of scripts in `scripts/` to the Readme.

- [x] deployGH-Pages.sh
- [x] fixAllFileComments.sh
- [x] fixSingleFileComment.sh

**Comment by neumantm** [comment]
Documentation added in the [wiki](https://github.com/AmyAssist/Amy/wiki/How-to-use-the-script-tools) instead of the readme, because the scripts are mainly for developers, not end users.
