### ISSUE TITLE
Smartphone-SR (local audio stream)

### ISSUE THREAD

**Issue by Bensge** [AmyAssist/Amy#81]
As a user I want to use SR on my smartphone and have the audio streamed to the Amy instance

20 SP

Prio 10

Tasks:
- [ ] Create audio stream in the WebApp (JS), send to server
- [ ] Receive audio stream in server and feed into SR
- [ ] Send Amy results back to WebApp
- [ ] Present Amy response in WebApp UI

**Comment by Legion2** [comment]
discarded
